#!/usr/bin/env python3
from __future__ import annotations

GAP_KEYS: dict[str, dict[str, str]] = {
    "%lld 分钟前更新": {
        "en": "Updated %lld min ago",
        "zh-Hans": "%lld 分钟前更新",
        "zh-Hant": "%lld 分鐘前更新",
        "es": "%lld actualizado hace minutos",
        "pt": "%lld atualizado minutos atrás",
        "ar": "%lld تم التحديث منذ دقائق",
        "hi": "%lld मिनट पहले अपडेट किया गया",
        "fr": "%lld mis à jour il y a quelques minutes",
        "ta": "%lld நிமிடங்களுக்கு முன்பு புதுப்பிக்கப்பட்டது"
    },
    "%lld%%": {
        "en": "%lld%%",
        "zh-Hans": "%lld%%",
        "zh-Hant": "%lld%%",
        "es": "%lld%%",
        "pt": "%lld%%",
        "ar": "%lld%%",
        "hi": "%lld%%",
        "fr": "%lld%%",
        "ta": "%lld%%"
    },
    "AI 返回的数据无法解析，请重试。": {
        "en": "Could not parse the data returned by AI. Please try again.",
        "zh-Hans": "AI 返回的数据无法解析，请重试。",
        "zh-Hant": "AI 傳回的資料無法解析，請重試。",
        "es": "AI Los datos devueltos no se pudieron analizar, inténtelo de nuevo.",
        "pt": "AI Os dados retornados não puderam ser analisados, tente novamente.",
        "ar": "AI لا يمكن تحليل البيانات التي تم إرجاعها، يرجى المحاولة مرة أخرى.",
        "hi": "AI लौटाया गया डेटा पार्स नहीं किया जा सका, कृपया पुनः प्रयास करें।",
        "fr": "AI Les données renvoyées n'ont pas pu être analysées, veuillez réessayer.",
        "ta": "AI திரும்பிய தரவை பாகுபடுத்த முடியவில்லை, மீண்டும் முயற்சிக்கவும்."
    },
    "切换群组，%@": {
        "en": "Switch groups, %@",
        "zh-Hans": "切换群组，%@",
        "zh-Hant": "切換群組，%@",
        "es": "Cambiar de grupo, %@",
        "pt": "Trocar de grupo, %@",
        "ar": "تبديل المجموعات، %@",
        "hi": "समूह स्विच करें, %@",
        "fr": "Changer de groupe, %@",
        "ta": "குழுக்களை மாற்றவும், %@"
    },
    "图片上传失败，请检查网络后重试。": {
        "en": "Image upload failed, please check the network and try again.",
        "zh-Hans": "图片上传失败，请检查网络后重试。",
        "zh-Hant": "圖片上傳失敗，請檢查網路後重試。",
        "es": "Error al cargar la imagen, verifique la red e inténtelo nuevamente.",
        "pt": "Falha no upload da imagem. Verifique a rede e tente novamente.",
        "ar": "فشل تحميل الصورة، يرجى التحقق من الشبكة والمحاولة مرة أخرى.",
        "hi": "छवि अपलोड विफल रहा, कृपया नेटवर्क जांचें और पुनः प्रयास करें।",
        "fr": "Le téléchargement de l'image a échoué, veuillez vérifier le réseau et réessayer.",
        "ta": "படப் பதிவேற்றம் தோல்வியடைந்தது, நெட்வொர்க்கைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்."
    },
    "图片加载失败": {
        "en": "Image loading failed",
        "zh-Hans": "图片加载失败",
        "zh-Hant": "圖片載入失敗",
        "es": "Error al cargar la imagen",
        "pt": "Falha no carregamento da imagem",
        "ar": "فشل تحميل الصورة",
        "hi": "छवि लोडिंग विफल रही",
        "fr": "Échec du chargement de l'image",
        "ta": "படத்தை ஏற்றுவதில் தோல்வி"
    },
    "定位到我的位置": {
        "en": "Locate my location",
        "zh-Hans": "定位到我的位置",
        "zh-Hant": "定位到我的位置",
        "es": "Localizar mi ubicación",
        "pt": "Localizar minha localização",
        "ar": "تحديد موقعي",
        "hi": "मेरे स्थान का पता लगाएँ",
        "fr": "Localiser mon emplacement",
        "ta": "எனது இருப்பிடத்தைக் கண்டுபிடி"
    },
    "拖选文字后可复制": {
        "en": "Drag and select text to copy",
        "zh-Hans": "拖选文字后可复制",
        "zh-Hant": "拖選文字後可複製",
        "es": "Arrastra y selecciona el texto para copiar",
        "pt": "Arraste e selecione o texto para copiar",
        "ar": "اسحب النص وحدده لنسخه",
        "hi": "कॉपी करने के लिए टेक्स्ट को खींचें और चुनें",
        "fr": "Faites glisser et sélectionnez le texte à copier",
        "ta": "நகலெடுக்க உரையை இழுத்து தேர்ந்தெடுக்கவும்"
    },
    "放弃": {
        "en": "give up",
        "zh-Hans": "放弃",
        "zh-Hant": "放棄",
        "es": "rendirse",
        "pt": "desistir",
        "ar": "استسلم",
        "hi": "छोड़ दो",
        "fr": "abandonner",
        "ta": "விட்டுவிடுங்கள்"
    },
    "没有可预览的附件": {
        "en": "No attachments available for preview",
        "zh-Hans": "没有可预览的附件",
        "zh-Hant": "沒有可預覽的附件",
        "es": "No hay archivos adjuntos disponibles para vista previa",
        "pt": "Nenhum anexo disponível para visualização",
        "ar": "لا توجد مرفقات متاحة للمعاينة",
        "hi": "पूर्वावलोकन के लिए कोई अनुलग्नक उपलब्ध नहीं है",
        "fr": "Aucune pièce jointe disponible pour l'aperçu",
        "ta": "முன்னோட்டத்திற்கு இணைப்புகள் எதுவும் இல்லை"
    },
    "请先登录后再使用 AI 识图创建任务。": {
        "en": "Please log in first before using AI to create a task for image recognition.",
        "zh-Hans": "请先登录后再使用 AI 识图创建任务。",
        "zh-Hant": "請先登入後再使用 AI 識圖建立任務。",
        "es": "Inicie sesión primero antes de usar AI para crear una tarea de reconocimiento de imágenes.",
        "pt": "Faça login primeiro antes de usar AI para criar uma tarefa para reconhecimento de imagem.",
        "ar": "يرجى تسجيل الدخول أولاً قبل استخدام AI لإنشاء مهمة للتعرف على الصور.",
        "hi": "छवि पहचान के लिए कार्य बनाने के लिए AI का उपयोग करने से पहले कृपया लॉग इन करें।",
        "fr": "Veuillez d'abord vous connecter avant d'utiliser AI pour créer une tâche de reconnaissance d'image.",
        "ta": "AI ஐப் பயன்படுத்துவதற்கு முன் முதலில் உள்நுழையவும், படத்தை அறிதலுக்கான பணியை உருவாக்கவும்."
    },
    "预览附件": {
        "en": "Preview attachment",
        "zh-Hans": "预览附件",
        "zh-Hant": "預覽附件",
        "es": "Vista previa del archivo adjunto",
        "pt": "Visualizar anexo",
        "ar": "معاينة المرفق",
        "hi": "पूर्वावलोकन अनुलग्नक",
        "fr": "Aperçu de la pièce jointe",
        "ta": "இணைப்பு முன்னோட்டம்"
    },
    "交美术课材料费": {
        "en": "Pay art class material fee",
        "zh-Hans": "交美术课材料费",
        "zh-Hant": "交美術課材料費",
        "es": "Pagar la tarifa del material de la clase de arte.",
        "pt": "Pagar taxa de material de aula de arte",
        "ar": "دفع رسوم المواد الفنية",
        "hi": "कला वर्ग सामग्री शुल्क का भुगतान करें",
        "fr": "Payer les frais de matériel de cours d'art",
        "ta": "கலை வகுப்பு பொருள் கட்டணம் செலுத்தவும்"
    },
    "从混乱到清晰。\n一起，完美同步。": {
        "en": "From chaos to clarity.\nTogether, perfectly synced.",
        "zh-Hans": "从混乱到清晰。\n一起，完美同步。",
        "zh-Hant": "從混亂到清晰。\n在一起，完美同步。",
        "es": "Del caos a la claridad.\nJuntos, perfectamente sincronizados.",
        "pt": "Do caos à clareza.\nJuntos, perfeitamente sincronizados.",
        "ar": "من الفوضى إلى الوضوح.\nمعًا، متزامنين تمامًا.",
        "hi": "अराजकता से स्पष्टता की ओर.\nएक साथ, पूरी तरह से समन्वयित।",
        "fr": "Du chaos à la clarté.\nEnsemble, parfaitement synchronisés.",
        "ta": "குழப்பத்திலிருந்து தெளிவு வரை.\nஒன்றாக, சரியாக ஒத்திசைக்கப்பட்டது."
    },
    "从混乱到清晰。": {
        "en": "From chaos to clarity.",
        "zh-Hans": "从混乱到清晰。",
        "zh-Hant": "從混亂到清晰。",
        "es": "Del caos a la claridad.",
        "pt": "Do caos à clareza.",
        "ar": "من الفوضى إلى الوضوح.",
        "hi": "अराजकता से स्पष्टता की ओर.",
        "fr": "Du chaos à la clarté.",
        "ta": "குழப்பத்திலிருந்து தெளிவு வரை."
    },
    "体检复查": {
        "en": "Physical examination review",
        "zh-Hans": "体检复查",
        "zh-Hant": "體檢複查",
        "es": "Revisión del examen físico",
        "pt": "Revisão do exame físico",
        "ar": "مراجعة الفحص البدني",
        "hi": "शारीरिक परीक्षण समीक्षा",
        "fr": "Révision de l'examen physique",
        "ta": "உடல் பரிசோதனை ஆய்வு"
    },
    "右上角控制点": {
        "en": "Upper right corner control point",
        "zh-Hans": "右上角控制点",
        "zh-Hant": "右上角控制點",
        "es": "Punto de control de la esquina superior derecha",
        "pt": "Ponto de controle no canto superior direito",
        "ar": "نقطة التحكم في الزاوية اليمنى العليا",
        "hi": "ऊपरी दायां कोना नियंत्रण बिंदु",
        "fr": "Point de contrôle dans le coin supérieur droit",
        "ta": "மேல் வலது மூலையில் கட்டுப்பாட்டு புள்ளி"
    },
    "右下角控制点": {
        "en": "Lower right corner control point",
        "zh-Hans": "右下角控制点",
        "zh-Hant": "右下角控制點",
        "es": "Punto de control de la esquina inferior derecha",
        "pt": "Ponto de controle no canto inferior direito",
        "ar": "نقطة التحكم في الزاوية اليمنى السفلى",
        "hi": "निचला दायां कोना नियंत्रण बिंदु",
        "fr": "Point de contrôle du coin inférieur droit",
        "ta": "கீழ் வலது மூலையில் கட்டுப்பாட்டு புள்ளி"
    },
    "左上角控制点": {
        "en": "upper left control point",
        "zh-Hans": "左上角控制点",
        "zh-Hant": "左上角控制點",
        "es": "punto de control superior izquierdo",
        "pt": "ponto de controle superior esquerdo",
        "ar": "نقطة التحكم العلوية اليسرى",
        "hi": "ऊपरी बाएँ नियंत्रण बिंदु",
        "fr": "point de contrôle supérieur gauche",
        "ta": "மேல் இடது கட்டுப்பாட்டு புள்ளி"
    },
    "左下角控制点": {
        "en": "Lower left corner control point",
        "zh-Hans": "左下角控制点",
        "zh-Hant": "左下角控制點",
        "es": "Punto de control de la esquina inferior izquierda",
        "pt": "Ponto de controle no canto inferior esquerdo",
        "ar": "نقطة التحكم في الزاوية اليسرى السفلية",
        "hi": "निचला बायां कोना नियंत्रण बिंदु",
        "fr": "Point de contrôle du coin inférieur gauche",
        "ta": "கீழ் இடது மூலையில் கட்டுப்பாட்டு புள்ளி"
    },
    "接放学": {
        "en": "Pick up and drop off from school",
        "zh-Hans": "接放学",
        "zh-Hant": "接放學",
        "es": "Recoger y dejar en la escuela.",
        "pt": "Pegar e entregar na escola",
        "ar": "التقاط والتوصيل من المدرسة",
        "hi": "स्कूल से लेना और छोड़ना",
        "fr": "Prise en charge et retour à l'école",
        "ta": "பள்ளியிலிருந்து அழைத்து வரவும்"
    },
    "接补习班": {
        "en": "Take cram school",
        "zh-Hans": "接补习班",
        "zh-Hant": "接補習班",
        "es": "Tomar escuela intensiva",
        "pt": "Faça cursinho",
        "ar": "خذ مدرسة كرام",
        "hi": "रटना स्कूल ले लो",
        "fr": "Prendre une école secondaire",
        "ta": "க்ராம் பள்ளியை எடுத்துக் கொள்ளுங்கள்"
    },
    "此日程由外部同步，暂不支持在应用内修改": {
        "en": "This schedule is synchronized externally and does not support modification within the app.",
        "zh-Hans": "此日程由外部同步，暂不支持在应用内修改",
        "zh-Hant": "此行程由外部同步，暫不支援在應用程式內修改",
        "es": "Este horario se sincroniza externamente y no admite modificaciones dentro de la aplicación.",
        "pt": "Esta programação é sincronizada externamente e não suporta modificação dentro do aplicativo.",
        "ar": "تتم مزامنة هذا الجدول خارجيًا ولا يدعم التعديل داخل التطبيق.",
        "hi": "यह शेड्यूल बाहरी रूप से सिंक्रनाइज़ है और ऐप के भीतर संशोधन का समर्थन नहीं करता है।",
        "fr": "Ce planning est synchronisé en externe et ne prend pas en charge les modifications au sein de l'application.",
        "ta": "இந்த அட்டவணை வெளிப்புறமாக ஒத்திசைக்கப்பட்டுள்ளது மற்றும் பயன்பாட்டில் மாற்றங்களை ஆதரிக்காது."
    },
    "登录会话尚未就绪，请稍后重试。": {
        "en": "The login session is not ready yet, please try again later.",
        "zh-Hans": "登录会话尚未就绪，请稍后重试。",
        "zh-Hant": "登入會話尚未就緒，請稍後重試。",
        "es": "La sesión de inicio de sesión aún no está lista; inténtelo nuevamente más tarde.",
        "pt": "A sessão de login ainda não está pronta. Tente novamente mais tarde.",
        "ar": "جلسة تسجيل الدخول ليست جاهزة بعد، يرجى المحاولة مرة أخرى لاحقًا.",
        "hi": "लॉगिन सत्र अभी तैयार नहीं है, कृपया बाद में पुनः प्रयास करें।",
        "fr": "La session de connexion n'est pas encore prête, veuillez réessayer plus tard.",
        "ta": "உள்நுழைவு அமர்வு இன்னும் தயாராகவில்லை, பின்னர் மீண்டும் முயற்சிக்கவும்."
    },
    "简体中文": {
        "en": "Simplified Chinese",
        "zh-Hans": "简体中文",
        "zh-Hant": "簡體中文",
        "es": "Chino simplificado",
        "pt": "Chinês simplificado",
        "ar": "الصينية المبسطة",
        "hi": "सरलीकृत चीनी",
        "fr": "Chinois simplifié",
        "ta": "எளிமைப்படுத்தப்பட்ட சீனம்"
    },
    "繁體中文": {
        "en": "Traditional Chinese",
        "zh-Hans": "繁體中文",
        "zh-Hant": "繁體中文",
        "es": "chino tradicional",
        "pt": "Chinês Tradicional",
        "ar": "الصينية التقليدية",
        "hi": "पारंपरिक चीनी",
        "fr": "Chinois traditionnel",
        "ta": "பாரம்பரிய சீன"
    },
    "%@ %@": {
        "en": "%1$@ %2$@",
        "zh-Hans": "%@ %@",
        "zh-Hant": "%@ %@",
        "es": "%1$@ %2$@",
        "pt": "%1$@ %2$@",
        "ar": "%1$@ %2$@",
        "hi": "%1$@ %2$@",
        "fr": "%1$@ %2$@",
        "ta": "%1$@ %2$@"
    },
    "%@ 即将推出。": {
        "en": "%@ coming soon.",
        "zh-Hans": "%@ 即将推出。",
        "zh-Hant": "%@ 即將推出。",
        "es": "%@ próximamente.",
        "pt": "%@ em breve.",
        "ar": "%@ قريبا.",
        "hi": "%@ जल्द ही आ रहा है।",
        "fr": "%@ à venir.",
        "ta": "%@ விரைவில்."
    },
    "%lld / %lld": {
        "en": "%1$lld / %2$lld",
        "zh-Hans": "%lld / %lld",
        "zh-Hant": "%lld / %lld",
        "es": "%1$lld / %2$lld",
        "pt": "%1$lld / %2$lld",
        "ar": "%1$lld / %2$lld",
        "hi": "%1$lld / %2$lld",
        "fr": "%1$lld / %2$lld",
        "ta": "%1$lld / %2$lld"
    },
    "👑 单任务无限图片、支持原图 (Original Quality)、解锁视频与文档 (PDF/Word) 上传。": {
        "en": "👑 Unlimited images per task, original quality, plus video and documents (PDF/Word).",
        "zh-Hans": "👑 单任务无限图片、支持原图 (Original Quality)、解锁视频与文档 (PDF/Word) 上传。",
        "zh-Hant": "👑 單任務無限圖片、支援原圖 (Original Quality)、解鎖影片與文件 (PDF/Word) 上傳。",
        "es": "👑 Imágenes ilimitadas por tarea, calidad original, además de videos y documentos (PDF/Word).",
        "pt": "👑 Imagens ilimitadas por tarefa, qualidade original, além de vídeos e documentos (PDF/Word).",
        "ar": "👑 صور غير محدودة لكل مهمة، بالجودة الأصلية، بالإضافة إلى الفيديو والمستندات (PDF/Word).",
        "hi": "👑 प्रति कार्य असीमित छवियां, मूल गुणवत्ता, साथ ही वीडियो और दस्तावेज़ (PDF/Word)।",
        "fr": "👑 Images illimitées par tâche, qualité originale, ainsi que vidéo et documents (PDF/Word).",
        "ta": "👑 ஒரு பணிக்கு வரம்பற்ற படங்கள், அசல் தரம், மேலும் வீடியோ மற்றும் ஆவணங்கள் (PDF/Word)."
    },
    "👑 无限创建与加入群组，无限成员人数。": {
        "en": "👑 Unlimited groups to create and join, unlimited members.",
        "zh-Hans": "👑 无限创建与加入群组，无限成员人数。",
        "zh-Hant": "👑 無限建立與加入群組，無限成員人數。",
        "es": "👑 Grupos ilimitados para crear y unirse, miembros ilimitados.",
        "pt": "👑 Grupos ilimitados para criar e participar, membros ilimitados.",
        "ar": "👑 مجموعات غير محدودة للإنشاء والانضمام، عدد غير محدود من الأعضاء.",
        "hi": "👑 असीमित समूह बनाने और शामिल होने के लिए, असीमित सदस्य।",
        "fr": "👑 Groupes illimités à créer et à rejoindre, membres illimités.",
        "ta": "👑 உருவாக்க மற்றும் சேர வரம்பற்ற குழுக்கள், வரம்பற்ற உறுப்பினர்கள்."
    },
    "🚀 创世用户福利：限时免费领取 1 年 Pro 权益！": {
        "en": "🚀 Founding member offer: claim 1 year of Pro free for a limited time!",
        "zh-Hans": "🚀 创世用户福利：限时免费领取 1 年 Pro 权益！",
        "zh-Hant": "🚀 創世用戶福利：限時免費領取 1 年 Pro 權益！",
        "es": "🚀 Oferta para miembro fundador: ¡reclama 1 año de Pro gratis por tiempo limitado!",
        "pt": "🚀 Oferta para membro fundador: reivindique 1 ano de Pro grátis por tempo limitado!",
        "ar": "🚀 عرض العضو المؤسس: احصل على سنة واحدة من Pro مجانًا لفترة محدودة!",
        "hi": "🚀 संस्थापक सदस्य प्रस्ताव: सीमित समय के लिए 1 वर्ष के लिए Pro का निःशुल्क दावा करें!",
        "fr": "🚀 Offre membre fondateur : bénéficiez de 1 an de Pro gratuit pour une durée limitée !",
        "ta": "🚀 ஸ்தாபக உறுப்பினர் சலுகை: குறிப்பிட்ட காலத்திற்கு Pro 1 வருடத்தை இலவசமாகப் பெறுங்கள்!"
    },
    "AI 语音极速建任务、群组智能周报、高阶提醒规则等更多专属功能即将上线。": {
        "en": "AI voice task creation, group smart weekly reports, advanced reminders, and more Pro features are on the way.",
        "zh-Hans": "AI 语音极速建任务、群组智能周报、高阶提醒规则等更多专属功能即将上线。",
        "zh-Hant": "AI 語音極速建任務、群組智慧週報、高階提醒規則等更多專屬功能即將上線。",
        "es": "AI creación de tareas de voz, informes semanales inteligentes grupales, recordatorios avanzados y más funciones Pro están en camino.",
        "pt": "AI criação de tarefas de voz, relatórios semanais inteligentes de grupo, lembretes avançados e mais recursos Pro estão a caminho.",
        "ar": "AI إنشاء المهام الصوتية والتقارير الأسبوعية الجماعية الذكية والتذكيرات المتقدمة والمزيد من ميزات Pro في الطريق.",
        "hi": "AI ध्वनि कार्य निर्माण, समूह स्मार्ट साप्ताहिक रिपोर्ट, उन्नत अनुस्मारक, और अधिक Pro सुविधाएँ आने वाली हैं।",
        "fr": "La création de tâches vocales AI, les rapports hebdomadaires intelligents de groupe, les rappels avancés et d'autres fonctionnalités Pro sont en route.",
        "ta": "AI குரல் பணி உருவாக்கம், குழு ஸ்மார்ட் வாராந்திர அறிக்கைகள், மேம்பட்ட நினைவூட்டல்கள் மற்றும் பல Pro அம்சங்கள் தயாராக உள்ளன."
    },
    "Apple 登录成功": {
        "en": "Signed in with Apple",
        "zh-Hans": "Apple 登录成功",
        "zh-Hant": "Apple 登入成功",
        "es": "Inicia sesión con Apple",
        "pt": "Conectado com Apple",
        "ar": "تم تسجيل الدخول باستخدام Apple",
        "hi": "Apple के साथ साइन इन किया गया",
        "fr": "Connecté avec Apple",
        "ta": "Apple மூலம் உள்நுழைந்துள்ளீர்கள்"
    },
    "Pro 版": {
        "en": "Pro",
        "zh-Hans": "Pro 版",
        "zh-Hant": "Pro 版",
        "es": "Pro",
        "pt": "Pro",
        "ar": "Pro",
        "hi": "Pro",
        "fr": "Pro",
        "ta": "Pro"
    },
    "Supabase SDK 尚未接入，请先添加依赖。": {
        "en": "Supabase SDK is not available in this build. Please add the dependency first.",
        "zh-Hans": "Supabase SDK 尚未接入，请先添加依赖。",
        "zh-Hant": "Supabase SDK 尚未接入，請先新增依賴。",
        "es": "Supabase SDK no está disponible en esta compilación. Primero agregue la dependencia.",
        "pt": "Supabase SDK não está disponível nesta compilação. Adicione a dependência primeiro.",
        "ar": "Supabase SDK غير متوفر في هذا الإصدار. الرجاء إضافة التبعية أولاً.",
        "hi": "इस बिल्ड में Supabase SDK उपलब्ध नहीं है। कृपया पहले निर्भरता जोड़ें.",
        "fr": "Supabase SDK n'est pas disponible dans cette version. Veuillez d'abord ajouter la dépendance.",
        "ta": "இந்த கட்டமைப்பில் Supabase SDK கிடைக்கவில்லை. முதலில் சார்புநிலையைச் சேர்க்கவும்."
    },
    "Supabase 配置无效，请检查 URL 与 Anon Key。": {
        "en": "Invalid Supabase configuration. Please check the URL and anon key.",
        "zh-Hans": "Supabase 配置无效，请检查 URL 与 Anon Key。",
        "zh-Hant": "Supabase 配置無效，請檢查 URL 與 Anon Key。",
        "es": "Configuración Supabase no válida. Verifique la clave URL y anon.",
        "pt": "Configuração Supabase inválida. Por favor, verifique a chave URL e anon.",
        "ar": "تكوين Supabase غير صالح. يرجى التحقق من URL ومفتاح حالاً.",
        "hi": "अमान्य Supabase कॉन्फ़िगरेशन. कृपया URL और anon कुंजी की जाँच करें।",
        "fr": "Configuration Supabase invalide. Veuillez vérifier le URL et la clé anon.",
        "ta": "தவறான Supabase உள்ளமைவு. தயவுசெய்து URL மற்றும் anon விசையைச் சரிபார்க்கவும்."
    },
    "VIP 权益即将开放。": {
        "en": "VIP benefits coming soon.",
        "zh-Hans": "VIP 权益即将开放。",
        "zh-Hant": "VIP 權益即將開放。",
        "es": "Beneficios de VIP próximamente.",
        "pt": "Benefícios VIP em breve.",
        "ar": "VIP الفوائد قريبا.",
        "hi": "VIP लाभ जल्द ही आ रहा है।",
        "fr": "Les avantages VIP seront bientôt disponibles.",
        "ta": "VIP பலன்கள் விரைவில்."
    },
    "为 %@ 预订生日餐厅/场地": {
        "en": "Book birthday restaurant/venue for %@",
        "zh-Hans": "为 %@ 预订生日餐厅/场地",
        "zh-Hant": "為 %@ 預訂生日餐廳/場地",
        "es": "Reserva restaurante/lugar de cumpleaños para %@",
        "pt": "Reserve restaurante/local de aniversário para %@",
        "ar": "حجز مطعم/مكان عيد ميلاد لـ %@",
        "hi": "%@ के लिए जन्मदिन रेस्तरां/स्थान बुक करें",
        "fr": "Réservez un restaurant/salle d'anniversaire pour %@",
        "ta": "%@ க்கு பிறந்தநாள் உணவகம்/இடத்தை பதிவு செய்யவும்"
    },
    "任务写入失败：群组上下文不一致。": {
        "en": "Failed to save task: Inconsistent group context.",
        "zh-Hans": "任务写入失败：群组上下文不一致。",
        "zh-Hant": "任務寫入失敗：群組上下文不一致。",
        "es": "No se pudo guardar la tarea: contexto de grupo inconsistente.",
        "pt": "Falha ao salvar a tarefa: contexto de grupo inconsistente.",
        "ar": "فشل حفظ المهمة: سياق المجموعة غير متناسق.",
        "hi": "कार्य सहेजने में विफल: असंगत समूह संदर्भ।",
        "fr": "Échec de l'enregistrement de la tâche : contexte de groupe incohérent.",
        "ta": "பணியைச் சேமிப்பதில் தோல்வி: சீரற்ற குழு சூழல்."
    },
    "任务即将开始": {
        "en": "Task starting soon",
        "zh-Hans": "任务即将开始",
        "zh-Hant": "任務即將開始",
        "es": "Tarea que comienza pronto",
        "pt": "Tarefa começando em breve",
        "ar": "ستبدأ المهمة قريبًا",
        "hi": "कार्य शीघ्र प्रारंभ हो रहा है",
        "fr": "Tâche commençant bientôt",
        "ta": "விரைவில் பணி தொடங்கும்"
    },
    "任务附件与媒体库": {
        "en": "Task attachments & media",
        "zh-Hans": "任务附件与媒体库",
        "zh-Hant": "任務附件與媒體庫",
        "es": "Archivos adjuntos y medios de tareas",
        "pt": "Anexos de tarefas e mídia",
        "ar": "مرفقات المهام والوسائط",
        "hi": "कार्य अनुलग्नक और मीडिया",
        "fr": "Pièces jointes et médias de tâches",
        "ta": "பணி இணைப்புகள் & மீடியா"
    },
    "体重": {
        "en": "Weight",
        "zh-Hans": "体重",
        "zh-Hant": "體重",
        "es": "Peso",
        "pt": "Peso",
        "ar": "الوزن",
        "hi": "वज़न",
        "fr": "Poids",
        "ta": "எடை"
    },
    "保存失败：%@": {
        "en": "Save failed: %@",
        "zh-Hans": "保存失败：%@",
        "zh-Hant": "保存失敗：%@",
        "es": "Error al guardar: %@",
        "pt": "Falha ao salvar: %@",
        "ar": "فشل الحفظ: %@",
        "hi": "सहेजना विफल: %@",
        "fr": "Échec de l'enregistrement : %@",
        "ta": "Save failed: %@"
    },
    "免费版": {
        "en": "Free",
        "zh-Hans": "免费版",
        "zh-Hant": "免費版",
        "es": "Gratis",
        "pt": "Grátis",
        "ar": "مجاني",
        "hi": "निःशुल्क",
        "fr": "Gratuit",
        "ta": "இலவசம்"
    },
    "免费版每任务仅支持 1 张图片，升级 Pro 可上传更多附件。": {
        "en": "Free plan allows 1 compressed image per task. Upgrade to Pro for more attachments.",
        "zh-Hans": "免费版每任务仅支持 1 张图片，升级 Pro 可上传更多附件。",
        "zh-Hant": "免費版每任務僅支援 1 張圖片，升級 Pro 可上傳更多附件。",
        "es": "El plan gratuito permite 1 imagen comprimida por tarea. Actualice a Pro para obtener más archivos adjuntos.",
        "pt": "O plano gratuito permite 1 imagem compactada por tarefa. Atualize para Pro para mais anexos.",
        "ar": "تسمح الخطة المجانية بصورة واحدة مضغوطة لكل مهمة. قم بالترقية إلى Pro لمزيد من المرفقات.",
        "hi": "निःशुल्क योजना प्रति कार्य 1 संपीड़ित छवि की अनुमति देती है। अधिक अनुलग्नकों के लिए Pro पर अपग्रेड करें।",
        "fr": "Le plan gratuit permet 1 image compressée par tâche. Passez à Pro pour plus de pièces jointes.",
        "ta": "இலவச திட்டம் ஒரு பணிக்கு 1 சுருக்கப்பட்ட படத்தை அனுமதிக்கிறது. கூடுதல் இணைப்புகளுக்கு Pro க்கு மேம்படுத்தவும்."
    },
    "免费领取 1 年 Pro 权益": {
        "en": "Claim 1 Year Pro for Free",
        "zh-Hans": "免费领取 1 年 Pro 权益",
        "zh-Hant": "免費領取 1 年 Pro 權益",
        "es": "Reclama 1 año Pro gratis",
        "pt": "Reivindique 1 ano Pro gratuitamente",
        "ar": "احصل على سنة واحدة Pro مجانًا",
        "hi": "1 वर्ष Pro का निःशुल्क दावा करें",
        "fr": "Réclamez 1 an Pro gratuitement",
        "ta": "1 வருடம் Proஐ இலவசமாகப் பெறுங்கள்"
    },
    "全天任务提醒": {
        "en": "All-day task reminder",
        "zh-Hans": "全天任务提醒",
        "zh-Hant": "全天任務提醒",
        "es": "Recordatorio de tareas durante todo el día",
        "pt": "Lembrete de tarefas durante todo o dia",
        "ar": "تذكير المهام طوال اليوم",
        "hi": "पूरे दिन का कार्य अनुस्मारक",
        "fr": "Rappel de tâches toute la journée",
        "ta": "நாள் முழுவதும் பணி நினைவூட்டல்"
    },
    "最多 1 个群组，每组上限 2 人。": {
        "en": "Up to 1 group, 2 members per group.",
        "zh-Hans": "最多 1 个群组，每组上限 2 人。",
        "zh-Hant": "最多 1 個群組，每組上限 2 人。",
        "es": "Hasta 1 grupo, 2 miembros por grupo.",
        "pt": "Até 1 grupo, 2 membros por grupo.",
        "ar": "ما يصل إلى مجموعة واحدة، عضوين لكل مجموعة.",
        "hi": "1 समूह तक, प्रति समूह 2 सदस्य।",
        "fr": "Jusqu'à 1 groupe, 2 membres par groupe.",
        "ta": "1 குழு வரை, ஒரு குழுவிற்கு 2 உறுப்பினர்கள்."
    },
    "准备 %@ 的生日愿望清单": {
        "en": "Prepare birthday wish list for %@",
        "zh-Hans": "准备 %@ 的生日愿望清单",
        "zh-Hant": "準備 %@ 的生日願望清單",
        "es": "Prepare la lista de deseos de cumpleaños para %@",
        "pt": "Prepare a lista de desejos de aniversário para %@",
        "ar": "قم بإعداد قائمة أمنيات عيد الميلاد لـ %@",
        "hi": "%@ के लिए जन्मदिन की इच्छा सूची तैयार करें",
        "fr": "Préparez une liste de souhaits d'anniversaire pour %@",
        "ta": "%@க்கான பிறந்தநாள் வாழ்த்துப் பட்டியலைத் தயாரிக்கவும்"
    },
    "切换群组": {
        "en": "Switch group",
        "zh-Hans": "切换群组",
        "zh-Hant": "切換群組",
        "es": "Cambiar grupo",
        "pt": "Mudar de grupo",
        "ar": "تبديل المجموعة",
        "hi": "समूह बदलें",
        "fr": "Groupe de commutation",
        "ta": "குழுவை மாற்றவும்"
    },
    "创建者权限已转移给「%@」。": {
        "en": "Creator permissions have been transferred to \"%@\".",
        "zh-Hans": "创建者权限已转移给「%@」。",
        "zh-Hant": "創建者權限已轉移給“%@”。",
        "es": "Los permisos de creador se han transferido a \"%@\".",
        "pt": "As permissões do criador foram transferidas para \"%@\".",
        "ar": "تم نقل أذونات المنشئ إلى \"%@\".",
        "hi": "निर्माता की अनुमतियाँ \"%@\" में स्थानांतरित कर दी गई हैं।",
        "fr": "Les autorisations du créateur ont été transférées vers \"%@\".",
        "ta": "படைப்பாளர் அனுமதிகள் \"%@\"க்கு மாற்றப்பட்டுள்ளன."
    },
    "删除后该虚拟成员的所有信息将不可恢复。": {
        "en": "This virtual member profile cannot be recovered after deletion.",
        "zh-Hans": "删除后该虚拟成员的所有信息将不可恢复。",
        "zh-Hant": "刪除後該虛擬成員的所有資訊將不可恢復。",
        "es": "Este perfil de miembro virtual no se puede recuperar después de eliminarlo.",
        "pt": "Este perfil de membro virtual não pode ser recuperado após a exclusão.",
        "ar": "لا يمكن استرداد ملف تعريف العضو الظاهري هذا بعد الحذف.",
        "hi": "इस वर्चुअल सदस्य प्रोफ़ाइल को हटाने के बाद पुनर्प्राप्त नहीं किया जा सकता है।",
        "fr": "Ce profil de membre virtuel ne peut pas être récupéré après suppression.",
        "ta": "இந்த மெய்நிகர் உறுப்பினர் சுயவிவரத்தை நீக்கிய பிறகு மீட்டெடுக்க முடியாது."
    },
    "删除该成员档案": {
        "en": "Delete member profile",
        "zh-Hans": "删除该成员档案",
        "zh-Hant": "刪除該成員檔案",
        "es": "Eliminar perfil de miembro",
        "pt": "Excluir perfil de membro",
        "ar": "حذف الملف الشخصي للعضو",
        "hi": "सदस्य प्रोफ़ाइल हटाएँ",
        "fr": "Supprimer le profil du membre",
        "ta": "உறுப்பினர் சுயவிவரத்தை நீக்கவும்"
    },
    "加入已有群组": {
        "en": "Join a Group",
        "zh-Hans": "加入已有群组",
        "zh-Hant": "加入已有群組",
        "es": "Únete a un grupo",
        "pt": "Junte-se a um grupo",
        "ar": "انضم إلى مجموعة",
        "hi": "एक समूह में शामिल हों",
        "fr": "Rejoindre un groupe",
        "ta": "ஒரு குழுவில் சேரவும்"
    },
    "升级至 Pro 高级版": {
        "en": "Upgrade to Pro",
        "zh-Hans": "升级至 Pro 高级版",
        "zh-Hant": "升級至 Pro 高級版",
        "es": "Actualiza a Pro",
        "pt": "Atualize para Pro",
        "ar": "الترقية إلى Pro",
        "hi": "Pro पर अपग्रेड करें",
        "fr": "Mise à niveau vers Pro",
        "ta": "Pro க்கு மேம்படுத்தவும்"
    },
    "压缩后图片数据为空，请重试。": {
        "en": "Compressed image data was empty. Please try again.",
        "zh-Hans": "压缩后图片数据为空，请重试。",
        "zh-Hant": "壓縮後圖片資料為空，請重試。",
        "es": "Los datos de la imagen comprimida estaban vacíos. Por favor inténtalo de nuevo.",
        "pt": "Os dados da imagem compactada estavam vazios. Por favor, tente novamente.",
        "ar": "كانت بيانات الصورة المضغوطة فارغة. يرجى المحاولة مرة أخرى.",
        "hi": "संपीड़ित छवि डेटा खाली था. कृपया पुन: प्रयास करें।",
        "fr": "Les données d'image compressées étaient vides. Veuillez réessayer.",
        "ta": "சுருக்கப்பட்ட படத் தரவு காலியாக இருந்தது. மீண்டும் முயற்சிக்கவும்."
    },
    "反馈写入失败：群组上下文不一致。": {
        "en": "Failed to save feedback: Inconsistent group context.",
        "zh-Hans": "反馈写入失败：群组上下文不一致。",
        "zh-Hant": "回饋寫入失敗：群組上下文不一致。",
        "es": "No se pudieron guardar los comentarios: contexto de grupo inconsistente.",
        "pt": "Falha ao salvar feedback: contexto de grupo inconsistente.",
        "ar": "فشل حفظ التعليقات: سياق المجموعة غير متناسق.",
        "hi": "फीडबैक सहेजने में विफल: असंगत समूह संदर्भ।",
        "fr": "Échec de l'enregistrement des commentaires : contexte de groupe incohérent.",
        "ta": "கருத்தைச் சேமிப்பதில் தோல்வி: சீரற்ற குழுச் சூழல்."
    },
    "只有当前群组的创建者才能转移权限。": {
        "en": "Only the current group creator can transfer ownership.",
        "zh-Hans": "只有当前群组的创建者才能转移权限。",
        "zh-Hant": "只有目前群組的建立者才能轉移權限。",
        "es": "Sólo el creador actual del grupo puede transferir la propiedad.",
        "pt": "Somente o criador atual do grupo pode transferir a propriedade.",
        "ar": "يمكن لمنشئ المجموعة الحالي فقط نقل الملكية.",
        "hi": "केवल वर्तमान समूह निर्माता ही स्वामित्व हस्तांतरित कर सकता है।",
        "fr": "Seul le créateur actuel du groupe peut transférer la propriété.",
        "ta": "தற்போதைய குழுவை உருவாக்கியவர் மட்டுமே உரிமையை மாற்ற முடியும்."
    },
    "后端尚未完成升级，请先执行最新 Supabase migration 后重试。": {
        "en": "Backend upgrade required. Please apply the latest Supabase migration and try again.",
        "zh-Hans": "后端尚未完成升级，请先执行最新 Supabase migration 后重试。",
        "zh-Hant": "後端尚未完成升級，請先執行最新 Supabase migration 後重試。",
        "es": "Se requiere actualización de backend. Aplique la última migración Supabase e inténtelo nuevamente.",
        "pt": "Atualização de back-end necessária. Aplique a migração Supabase mais recente e tente novamente.",
        "ar": "مطلوب ترقية الواجهة الخلفية. الرجاء تطبيق أحدث ترحيل Supabase والمحاولة مرة أخرى.",
        "hi": "बैकएंड अपग्रेड की आवश्यकता है. कृपया नवीनतम Supabase माइग्रेशन लागू करें और पुनः प्रयास करें।",
        "fr": "Mise à niveau du back-end requise. Veuillez appliquer la dernière migration Supabase et réessayer.",
        "ta": "பின்தள மேம்படுத்தல் தேவை. சமீபத்திய Supabase நகர்த்தலைப் பயன்படுத்தி, மீண்டும் முயற்சிக்கவும்."
    },
    "图片压缩失败，请重试。": {
        "en": "Image compression failed. Please try again.",
        "zh-Hans": "图片压缩失败，请重试。",
        "zh-Hant": "圖片壓縮失敗，請重試。",
        "es": "Falló la compresión de la imagen. Por favor inténtalo de nuevo.",
        "pt": "A compactação da imagem falhou. Por favor, tente novamente.",
        "ar": "فشل ضغط الصورة. يرجى المحاولة مرة أخرى.",
        "hi": "छवि संपीड़न विफल रहा. कृपया पुन: प्रयास करें।",
        "fr": "La compression de l'image a échoué. Veuillez réessayer.",
        "ta": "பட சுருக்கம் தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்."
    },
    "图片处理失败，请重试。": {
        "en": "Image processing failed. Please try again.",
        "zh-Hans": "图片处理失败，请重试。",
        "zh-Hant": "图片處理失败，请重试。",
        "es": "Error en el procesamiento de imágenes. Por favor inténtalo de nuevo.",
        "pt": "Falha no processamento da imagem. Por favor, tente novamente.",
        "ar": "فشلت معالجة الصورة. يرجى المحاولة مرة أخرى.",
        "hi": "छवि प्रसंस्करण विफल रहा. कृपया पुन: प्रयास करें।",
        "fr": "Le traitement de l'image a échoué. Veuillez réessayer.",
        "ta": "பட செயலாக்கம் தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்."
    },
    "图片格式解析失败，请换一张图片重试。": {
        "en": "Unsupported image format. Please try another photo.",
        "zh-Hans": "图片格式解析失败，请换一张图片重试。",
        "zh-Hant": "圖片格式解析失敗，請換一張圖片重試。",
        "es": "Formato de imagen no compatible. Por favor prueba con otra foto.",
        "pt": "Formato de imagem não suportado. Por favor, tente outra foto.",
        "ar": "تنسيق الصورة غير مدعوم. من فضلك حاول صورة أخرى.",
        "hi": "असमर्थित छवि प्रारूप. कृपया कोई अन्य फ़ोटो आज़माएँ.",
        "fr": "Format d'image non pris en charge. Veuillez essayer une autre photo.",
        "ta": "ஆதரிக்கப்படாத பட வடிவம். மற்றொரு புகைப்படத்தை முயற்சிக்கவும்."
    },
    "头像上传失败，请稍后再试。": {
        "en": "Avatar upload failed. Please try again later.",
        "zh-Hans": "头像上传失败，请稍后再试。",
        "zh-Hant": "頭像上傳失敗，請稍後再試。",
        "es": "La carga del avatar falló. Inténtelo de nuevo más tarde.",
        "pt": "Falha no upload do avatar. Por favor, tente novamente mais tarde.",
        "ar": "فشل تحميل الصورة الرمزية. يرجى المحاولة مرة أخرى لاحقا.",
        "hi": "अवतार अपलोड विफल रहा. कृपया बाद में पुन: प्रयास करें।",
        "fr": "Le téléchargement de l'avatar a échoué. Veuillez réessayer plus tard.",
        "ta": "அவதார் பதிவேற்றம் தோல்வியடைந்தது. பிறகு முயற்சிக்கவும்."
    },
    "头像数据为空，请重新选择图片后再试。": {
        "en": "Avatar data is empty. Please choose another photo and try again.",
        "zh-Hans": "头像数据为空，请重新选择图片后再试。",
        "zh-Hant": "頭像資料為空，請重新選擇圖片後再試。",
        "es": "Los datos del avatar están vacíos. Elige otra foto e inténtalo de nuevo.",
        "pt": "Os dados do avatar estão vazios. Escolha outra foto e tente novamente.",
        "ar": "بيانات الصورة الرمزية فارغة. الرجاء اختيار صورة أخرى والمحاولة مرة أخرى.",
        "hi": "अवतार डेटा खाली है. कृपया कोई अन्य फ़ोटो चुनें और पुनः प्रयास करें।",
        "fr": "Les données de l'avatar sont vides. Veuillez choisir une autre photo et réessayer.",
        "ta": "அவதார் தரவு காலியாக உள்ளது. மற்றொரு படத்தைத் தேர்ந்தெடுத்து மீண்டும் முயற்சிக்கவும்."
    },
    "女": {
        "en": "Female",
        "zh-Hans": "女",
        "zh-Hant": "女",
        "es": "Mujer",
        "pt": "Feminino",
        "ar": "أنثى",
        "hi": "स्त्री",
        "fr": "Femme",
        "ta": "பெண்"
    },
    "学校": {
        "en": "School",
        "zh-Hans": "学校",
        "zh-Hant": "學校",
        "es": "escuela",
        "pt": "Escola",
        "ar": "المدرسة",
        "hi": "स्कूल",
        "fr": "École",
        "ta": "பள்ளி"
    },
    "客户端鉴权失败，请检查 apikey。": {
        "en": "Client authentication failed. Please check the API key.",
        "zh-Hans": "客户端鉴权失败，请检查 apikey。",
        "zh-Hant": "客戶端鑑權失敗，請檢查 apikey。",
        "es": "Error de autenticación del cliente. Por favor verifique la clave API.",
        "pt": "A autenticação do cliente falhou. Por favor, verifique a chave API.",
        "ar": "فشلت مصادقة العميل. يرجى التحقق من مفتاح API.",
        "hi": "क्लाइंट प्रमाणीकरण विफल रहा. कृपया एपीआई कुंजी जांचें।",
        "fr": "L'authentification du client a échoué. Veuillez vérifier la clé API.",
        "ta": "கிளையண்ட் அங்கீகாரம் தோல்வியடைந்தது. API விசையைச் சரிபார்க்கவும்."
    },
    "将该成员移出群组": {
        "en": "Remove from group",
        "zh-Hans": "将该成员移出群组",
        "zh-Hant": "將該成員移出群組",
        "es": "Quitar del grupo",
        "pt": "Remover do grupo",
        "ar": "إزالة من المجموعة",
        "hi": "समूह से हटाएँ",
        "fr": "Supprimer du groupe",
        "ta": "குழுவிலிருந்து நீக்கு"
    },
    "已检测到有效登录会话": {
        "en": "A valid sign-in session was detected",
        "zh-Hans": "已检测到有效登录会话",
        "zh-Hant": "已偵測到有效登入會話",
        "es": "Se detectó una sesión entrante sig válida",
        "pt": "Uma sessão sign-in válida foi detectada",
        "ar": "تم اكتشاف جلسة دخول صالحة sign",
        "hi": "एक वैध sign-इन सत्र का पता चला",
        "fr": "Une session sign-in valide a été détectée",
        "ta": "சரியான sign அமர்வு கண்டறியப்பட்டது"
    },
    "布置现场并取回 %@ 的生日蛋糕": {
        "en": "Decorate venue and pick up birthday cake for %@",
        "zh-Hans": "布置现场并取回 %@ 的生日蛋糕",
        "zh-Hant": "佈置現場並取回 %@ 的生日蛋糕",
        "es": "Decora el lugar y recoge el pastel de cumpleaños para %@",
        "pt": "Decore o local e compre o bolo de aniversário para %@",
        "ar": "تزيين المكان والتقاط كعكة عيد ميلاد لـ %@",
        "hi": "आयोजन स्थल को सजाएँ और %@ के लिए जन्मदिन का केक उठाएँ",
        "fr": "Décorez la salle et récupérez le gâteau d'anniversaire pour %@",
        "ta": "இடத்தை அலங்கரித்து, %@க்கான பிறந்தநாள் கேக்கை எடுக்கவும்"
    },
    "年级": {
        "en": "Grade",
        "zh-Hans": "年级",
        "zh-Hant": "年級",
        "es": "Grado",
        "pt": "Nota",
        "ar": "الصف",
        "hi": "ग्रेड",
        "fr": "Note",
        "ta": "தரம்"
    },
    "当前操作尚未实现。": {
        "en": "This operation is not implemented yet.",
        "zh-Hans": "当前操作尚未实现。",
        "zh-Hant": "當前操作尚未實現。",
        "es": "Esta operación aún no está implementada.",
        "pt": "Esta operação ainda não está implementada.",
        "ar": "لم يتم تنفيذ هذه العملية بعد.",
        "hi": "यह ऑपरेशन अभी लागू नहीं हुआ है.",
        "fr": "Cette opération n'est pas encore mise en œuvre.",
        "ta": "இந்த செயல்பாடு இன்னும் செயல்படுத்தப்படவில்லை."
    },
    "当前没有权限移出或删除该成员。": {
        "en": "You don't have permission to remove or delete this member.",
        "zh-Hans": "当前没有权限移出或删除该成员。",
        "zh-Hant": "目前沒有權限移出或刪除該成員。",
        "es": "No tienes permiso para eliminar o eliminar a este miembro.",
        "pt": "Você não tem permissão para remover ou excluir este membro.",
        "ar": "ليس لديك الإذن بإزالة هذا العضو أو حذفه.",
        "hi": "आपके पास इस सदस्य को हटाने या हटाने की अनुमति नहीं है.",
        "fr": "Vous n'êtes pas autorisé à supprimer ou supprimer ce membre.",
        "ta": "இந்த உறுப்பினரை அகற்றவோ நீக்கவோ உங்களுக்கு அனுமதி இல்லை."
    },
    "当前没有权限编辑该资料。": {
        "en": "You do not have permission to edit this profile.",
        "zh-Hans": "当前没有权限编辑该资料。",
        "zh-Hant": "目前沒有權限編輯該資料。",
        "es": "No tienes permiso para editar este perfil.",
        "pt": "Você não tem permissão para editar este perfil.",
        "ar": "ليس لديك الإذن لتحرير هذا الملف الشخصي.",
        "hi": "आपको इस प्रोफ़ाइल को संपादित करने की अनुमति नहीं है.",
        "fr": "Vous n'êtes pas autorisé à modifier ce profil.",
        "ta": "இந்தச் சுயவிவரத்தைத் திருத்த உங்களுக்கு அனுமதி இல்லை."
    },
    "当前设备未配置邮件账户，请发送邮件至 %@。": {
        "en": "No mail account is configured. Please email %@.",
        "zh-Hans": "当前设备未配置邮件账户，请发送邮件至 %@。",
        "zh-Hant": "目前設備未配置郵件帳戶，請發送郵件至 %@。",
        "es": "No hay ninguna cuenta de correo configurada. Envíe un correo electrónico a %@.",
        "pt": "Nenhuma conta de e-mail está configurada. Por favor, envie um e-mail para %@.",
        "ar": "لم يتم تكوين أي حساب بريد. يرجى إرسال بريد إلكتروني إلى %@.",
        "hi": "कोई मेल खाता कॉन्फ़िगर नहीं किया गया है. कृपया %@ ईमेल करें।",
        "fr": "Aucun compte de messagerie n'est configuré. Veuillez envoyer un e-mail à %@.",
        "ta": "அஞ்சல் கணக்கு எதுவும் கட்டமைக்கப்படவில்லை. தயவுசெய்து மின்னஞ்சல் %@."
    },
    "当前设备未配置邮件账户，请发送邮件至 music.player.250617@gmail.com。": {
        "en": "No mail account is configured on this device. Please send an email to music.player.250617@gmail.com.",
        "zh-Hans": "当前设备未配置邮件账户，请发送邮件至 music.player.250617@gmail.com。",
        "zh-Hant": "目前設備未配置郵件帳戶，請發送郵件至 music.player.250617@gmail.com。",
        "es": "No hay ninguna cuenta de correo configurada en este dispositivo. Envíe un correo electrónico a music.player.250617@gmail.com.",
        "pt": "Nenhuma conta de e-mail está configurada neste dispositivo. Por favor, envie um e-mail para music.player.250617@gmail.com.",
        "ar": "لم يتم تكوين أي حساب بريد على هذا الجهاز. يرجى إرسال بريد إلكتروني إلى music.player.250617@gmail.com.",
        "hi": "इस डिवाइस पर कोई मेल खाता कॉन्फ़िगर नहीं है. कृपया music.player.250617@gmail.com को एक ईमेल भेजें।",
        "fr": "Aucun compte de messagerie n'est configuré sur cet appareil. Veuillez envoyer un e-mail à music.player.250617@gmail.com.",
        "ta": "இந்தச் சாதனத்தில் எந்த அஞ்சல் கணக்கும் உள்ளமைக்கப்படவில்லை. music.player.250617@gmail.com க்கு மின்னஞ்சல் அனுப்பவும்."
    },
    "您是「%@」等 %lld 个群组的创建者，请先转移权限或解散群组后再注销账户。": {
        "en": "You are the creator of %@ and %lld other groups. Please transfer ownership or dissolve those groups before deleting your account.",
        "zh-Hans": "您是「%@」等 %lld 个群组的创建者，请先转移权限或解散群组后再注销账户。",
        "zh-Hant": "您是「%@」等 %lld 個群組的創建者，請先轉移權限或解散群組後再登出帳戶。",
        "es": "Eres el creador de %@ y de %lld grupos más. Transfiere la propiedad o disuelve esos grupos antes de eliminar tu cuenta.",
        "pt": "Você é o criador de %@ e de mais %lld grupos. Transfira a propriedade ou dissolva esses grupos antes de excluir sua conta.",
        "ar": "أنت منشئ %@ و%lld مجموعات أخرى. يُرجى نقل الملكية أو حلّ تلك المجموعات قبل حذف حسابك.",
        "hi": "आप %@ सहित %lld अन्य समूहों के निर्माता हैं। कृपया खाता हटाने से पहले स्वामित्व स्थानांतरित करें या उन समूहों को भंग करें।",
        "fr": "Vous êtes le créateur de %@ et de %lld autres groupes. Veuillez transférer la propriété ou dissoudre ces groupes avant de supprimer votre compte.",
        "ta": "நீங்கள் %@ உட்பட மேலும் %lld குழுக்களின் உருவாக்குநர். கணக்கை நீக்குவதற்கு முன் உரிமையை மாற்றவும் அல்லது அந்தக் குழுக்களை கலைக்கவும்."
    },
    "您有一个待办任务": {
        "en": "You have a pending task",
        "zh-Hans": "您有一个待办任务",
        "zh-Hant": "您有一個待辦事項",
        "es": "Tienes una tarea pendiente",
        "pt": "Você tem uma tarefa pendente",
        "ar": "لديك مهمة معلقة",
        "hi": "आपका एक कार्य लंबित है",
        "fr": "Vous avez une tâche en attente",
        "ta": "உங்களிடம் பணி நிலுவையில் உள்ளது"
    },
    "成员创建失败：群组上下文不一致。": {
        "en": "Failed to create member: Inconsistent group context.",
        "zh-Hans": "成员创建失败：群组上下文不一致。",
        "zh-Hant": "成員建立失敗：群組上下文不一致。",
        "es": "No se pudo crear el miembro: contexto de grupo inconsistente.",
        "pt": "Falha ao criar membro: contexto de grupo inconsistente.",
        "ar": "فشل إنشاء العضو: سياق المجموعة غير متناسق.",
        "hi": "सदस्य बनाने में विफल: असंगत समूह संदर्भ।",
        "fr": "Échec de la création du membre : contexte de groupe incohérent.",
        "ta": "உறுப்பினரை உருவாக்குவதில் தோல்வி: சீரற்ற குழு சூழல்."
    },
    "成员档案": {
        "en": "Member Profile",
        "zh-Hans": "成员档案",
        "zh-Hant": "成員檔案",
        "es": "Miembro Proarchivo",
        "pt": "Membro Proarquivo",
        "ar": "عضو Proملف",
        "hi": "सदस्य Proफ़ाइल",
        "fr": "Membre Profichier",
        "ta": "உறுப்பினர் Profile"
    },
    "所选成员不符合接收权限的条件，请重新选择。": {
        "en": "The selected member cannot receive ownership. Please choose again.",
        "zh-Hans": "所选成员不符合接收权限的条件，请重新选择。",
        "zh-Hant": "所選成員不符合接收權限的條件，請重新選擇。",
        "es": "El miembro seleccionado no puede recibir la propiedad. Por favor elige de nuevo.",
        "pt": "O membro selecionado não pode receber propriedade. Por favor, escolha novamente.",
        "ar": "لا يمكن للعضو المحدد الحصول على الملكية. الرجاء الاختيار مرة أخرى.",
        "hi": "चयनित सदस्य को स्वामित्व प्राप्त नहीं हो सकता. कृपया पुनः चुनें.",
        "fr": "Le membre sélectionné ne peut pas recevoir la propriété. Veuillez choisir à nouveau.",
        "ta": "தேர்ந்தெடுக்கப்பட்ட உறுப்பினர் உரிமையைப் பெற முடியாது. மீண்டும் தேர்வு செய்யவும்."
    },
    "拍照": {
        "en": "Take Photo",
        "zh-Hans": "拍照",
        "zh-Hant": "拍照",
        "es": "tomar foto",
        "pt": "Tirar foto",
        "ar": "التقط صورة",
        "hi": "फ़ोटो लें",
        "fr": "Prendre une photo",
        "ta": "புகைப்படம் எடு"
    },
    "提前 %lld 分钟 · 任务即将开始": {
        "en": "%lld min before · task starting soon",
        "zh-Hans": "提前 %lld 分钟 · 任务即将开始",
        "zh-Hant": "提前 %lld 分鐘 · 任務即將開始",
        "es": "%lld min antes · tarea que comenzará pronto",
        "pt": "%lld min antes · tarefa começando em breve",
        "ar": "%lld دقيقة قبل · ستبدأ المهمة قريبًا",
        "hi": "%lld मिनट पहले · कार्य जल्द ही शुरू हो रहा है",
        "fr": "%lld min avant · la tâche commence bientôt",
        "ta": "%lld நிமிடத்திற்கு முன் · பணி விரைவில் தொடங்கும்"
    },
    "操作失败，请稍后重试。": {
        "en": "Action failed. Please try again later.",
        "zh-Hans": "操作失败，请稍后重试。",
        "zh-Hant": "操作失敗，請稍後重試。",
        "es": "La acción falló. Inténtelo de nuevo más tarde.",
        "pt": "A ação falhou. Por favor, tente novamente mais tarde.",
        "ar": "فشل الإجراء. يرجى المحاولة مرة أخرى لاحقا.",
        "hi": "कार्रवाई विफल रही. कृपया बाद में पुन: प्रयास करें।",
        "fr": "L'action a échoué. Veuillez réessayer plus tard.",
        "ta": "செயல் தோல்வியடைந்தது. பிறகு முயற்சிக்கவும்."
    },
    "敬请期待": {
        "en": "Coming soon",
        "zh-Hans": "敬请期待",
        "zh-Hant": "敬請期待",
        "es": "Próximamente",
        "pt": "Em breve",
        "ar": "قريبا",
        "hi": "जल्द आ रहा है",
        "fr": "Bientôt disponible",
        "ta": "விரைவில் வரும்"
    },
    "新建群组": {
        "en": "Create new group",
        "zh-Hans": "新建群组",
        "zh-Hant": "新建群組",
        "es": "Crear nuevo grupo",
        "pt": "Criar novo grupo",
        "ar": "إنشاء مجموعة جديدة",
        "hi": "नया समूह बनाएं",
        "fr": "Créer un nouveau groupe",
        "ta": "புதிய குழுவை உருவாக்கவும்"
    },
    "无法创建支持邮件，请稍后重试。": {
        "en": "Unable to open support email. Please try again later.",
        "zh-Hans": "无法创建支持邮件，请稍后重试。",
        "zh-Hant": "無法建立支援郵件，請稍後重試。",
        "es": "No se puede abrir el correo electrónico de soporte. Inténtelo de nuevo más tarde.",
        "pt": "Não foi possível abrir o e-mail de suporte. Por favor, tente novamente mais tarde.",
        "ar": "غير قادر على فتح البريد الإلكتروني للدعم. يرجى المحاولة مرة أخرى لاحقا.",
        "hi": "समर्थन ईमेल खोलने में असमर्थ. कृपया बाद में पुन: प्रयास करें।",
        "fr": "Impossible d'ouvrir l'e-mail d'assistance. Veuillez réessayer plus tard.",
        "ta": "ஆதரவு மின்னஞ்சலைத் திறக்க முடியவில்லை. பிறகு முயற்சிக்கவும்."
    },
    "有一则全天任务将于约定日期到来，请在日程中查看标题。": {
        "en": "An all-day task is due on the scheduled date. Open the app to see the title.",
        "zh-Hans": "有一则全天任务将于约定日期到来，请在日程中查看标题。",
        "zh-Hant": "有一則全天任務將於約定日期到來，請在行程中查看標題。",
        "es": "Una tarea de todo el día vence en la fecha programada. Abra la aplicación para ver el título.",
        "pt": "Uma tarefa de dia inteiro vence na data agendada. Abra o aplicativo para ver o título.",
        "ar": "مهمة لليوم كله مستحقة في التاريخ المجدول. افتح التطبيق لرؤية العنوان.",
        "hi": "निर्धारित तिथि पर पूरे दिन का कार्य होना है। शीर्षक देखने के लिए ऐप खोलें.",
        "fr": "Une tâche d'une journée entière est due à la date prévue. Ouvrez l'application pour voir le titre.",
        "ta": "திட்டமிடப்பட்ட தேதியில் ஒரு நாள் முழுவதும் வேலை செய்ய வேண்டும். தலைப்பைப் பார்க்க, பயன்பாட்டைத் திறக்கவும்."
    },
    "服务响应异常": {
        "en": "Unexpected server response",
        "zh-Hans": "服务响应异常",
        "zh-Hant": "服務響應異常",
        "es": "Respuesta inesperada del servidor",
        "pt": "Resposta inesperada do servidor",
        "ar": "استجابة الخادم غير متوقعة",
        "hi": "अप्रत्याशित सर्वर प्रतिक्रिया",
        "fr": "Réponse inattendue du serveur",
        "ta": "எதிர்பாராத சர்வர் பதில்"
    },
    "服务返回数据异常。": {
        "en": "Unexpected response from the server.",
        "zh-Hans": "服务返回数据异常。",
        "zh-Hant": "服務傳回資料異常。",
        "es": "Respuesta inesperada del servidor.",
        "pt": "Resposta inesperada do servidor.",
        "ar": "استجابة غير متوقعة من الخادم.",
        "hi": "सर्वर से अप्रत्याशित प्रतिक्रिया.",
        "fr": "Réponse inattendue du serveur.",
        "ta": "சர்வரில் இருந்து எதிர்பாராத பதில்."
    },
    "未命名组织": {
        "en": "Untitled Organization",
        "zh-Hans": "未命名组织",
        "zh-Hant": "未命名組織",
        "es": "Organización sin título",
        "pt": "Organização sem título",
        "ar": "منظمة بلا عنوان",
        "hi": "शीर्षक रहित संगठन",
        "fr": "Organisation sans titre",
        "ta": "பெயரிடப்படாத அமைப்பு"
    },
    "未知错误": {
        "en": "Unknown error",
        "zh-Hans": "未知错误",
        "zh-Hant": "未知錯誤",
        "es": "Error desconocido",
        "pt": "Erro desconhecido",
        "ar": "خطأ غير معروف",
        "hi": "अज्ञात त्रुटि",
        "fr": "Erreur inconnue",
        "ta": "அறியப்படாத பிழை"
    },
    "未知错误，请重试": {
        "en": "Unknown error. Please try again.",
        "zh-Hans": "未知错误，请重试",
        "zh-Hant": "未知錯誤，請重試",
        "es": "Error desconocido. Por favor inténtalo de nuevo.",
        "pt": "Erro desconhecido. Por favor, tente novamente.",
        "ar": "خطأ غير معروف. يرجى المحاولة مرة أخرى.",
        "hi": "अज्ञात त्रुटि. कृपया पुन: प्रयास करें।",
        "fr": "Erreur inconnue. Veuillez réessayer.",
        "ta": "அறியப்படாத பிழை. மீண்டும் முயற்சிக்கவும்."
    },
    "未能读取图片数据，请重新选择。": {
        "en": "Could not read image data. Please choose again.",
        "zh-Hans": "未能读取图片数据，请重新选择。",
        "zh-Hant": "未能讀取圖片數據，請重新選擇。",
        "es": "No se pudieron leer los datos de la imagen. Por favor elige de nuevo.",
        "pt": "Não foi possível ler os dados da imagem. Por favor, escolha novamente.",
        "ar": "لا يمكن قراءة بيانات الصورة. الرجاء الاختيار مرة أخرى.",
        "hi": "छवि डेटा नहीं पढ़ सका. कृपया पुनः चुनें.",
        "fr": "Impossible de lire les données d'image. Veuillez choisir à nouveau.",
        "ta": "படத் தரவைப் படிக்க முடியவில்லை. Please choose again."
    },
    "未设置": {
        "en": "Not Set",
        "zh-Hans": "未设置",
        "zh-Hant": "未設定",
        "es": "No establecido",
        "pt": "Não definido",
        "ar": "غير محدد",
        "hi": "सेट नहीं",
        "fr": "Non défini",
        "ta": "அமைக்கப்படவில்லை"
    },
    "权限已成功转移": {
        "en": "Ownership transferred successfully",
        "zh-Hans": "权限已成功转移",
        "zh-Hant": "權限已成功轉移",
        "es": "Propiedad transferida exitosamente",
        "pt": "Propriedade transferida com sucesso",
        "ar": "تم نقل الملكية بنجاح",
        "hi": "स्वामित्व सफलतापूर्वक स्थानांतरित हो गया",
        "fr": "Propriété transférée avec succès",
        "ta": "உரிமை வெற்றிகரமாக மாற்றப்பட்டது"
    },
    "权限转移失败，请稍后重试。": {
        "en": "Failed to transfer ownership. Please try again later.",
        "zh-Hans": "权限转移失败，请稍后重试。",
        "zh-Hant": "權限轉移失敗，請稍後重試。",
        "es": "No se pudo transferir la propiedad. Inténtelo de nuevo más tarde.",
        "pt": "Falha ao transferir a propriedade. Por favor, tente novamente mais tarde.",
        "ar": "تعذّر نقل الملكية. يرجى المحاولة مرة أخرى لاحقا.",
        "hi": "स्वामित्व हस्तांतरित करने में विफल. कृपया बाद में पुन: प्रयास करें।",
        "fr": "Échec du transfert de propriété. Veuillez réessayer plus tard.",
        "ta": "உரிமையை மாற்ற முடியவில்லை. பிறகு முயற்சிக்கவும்."
    },
    "查看附件": {
        "en": "View attachment",
        "zh-Hans": "查看附件",
        "zh-Hant": "查看附件",
        "es": "Ver archivo adjunto",
        "pt": "Ver anexo",
        "ar": "عرض المرفق",
        "hi": "अनुलग्नक देखें",
        "fr": "Afficher la pièce jointe",
        "ta": "இணைப்பைப் பார்க்கவும்"
    },
    "框选要识别的区域": {
        "en": "Select the area to recognize",
        "zh-Hans": "框选要识别的区域",
        "zh-Hant": "框选要識別的區域",
        "es": "Seleccione el área a reconocer",
        "pt": "Selecione a área a ser reconhecida",
        "ar": "حدد المنطقة للتعرف عليها",
        "hi": "पहचानने के लिए क्षेत्र का चयन करें",
        "fr": "Sélectionnez la zone à reconnaître",
        "ta": "அடையாளம் காண வேண்டிய பகுதியைத் தேர்ந்தெடுக்கவும்"
    },
    "每任务限 1 张压缩图片。": {
        "en": "1 compressed image per task.",
        "zh-Hans": "每任务限 1 张压缩图片。",
        "zh-Hant": "每任務限 1 張壓縮圖片。",
        "es": "1 imagen comprimida por tarea.",
        "pt": "1 imagem compactada por tarefa.",
        "ar": "1 صورة مضغوطة لكل مهمة.",
        "hi": "प्रति कार्य 1 संपीड़ित छवि।",
        "fr": "1 image compressée par tâche.",
        "ta": "ஒரு பணிக்கு 1 சுருக்கப்பட்ட படம்."
    },
    "消费成功：链接有效且已标记一次性使用": {
        "en": "Success: link is valid and marked as one-time use",
        "zh-Hans": "消费成功：链接有效且已标记一次性使用",
        "zh-Hant": "消費成功：連結有效且已標記一次性使用",
        "es": "Éxito: el enlace es válido y está marcado como de un solo uso.",
        "pt": "Sucesso: o link é válido e marcado como de uso único",
        "ar": "نجاح: الرابط صالح وتم وضع علامة عليه للاستخدام لمرة واحدة",
        "hi": "सफलता: लिंक वैध है और एक बार उपयोग के रूप में चिह्नित है",
        "fr": "Succès : le lien est valide et marqué comme à usage unique",
        "ta": "வெற்றி: இணைப்பு செல்லுபடியாகும் மற்றும் ஒருமுறை பயன்படுத்துவதாகக் குறிக்கப்பட்டது"
    },
    "消费邀请链接失败：%@": {
        "en": "Failed to consume invite link: %@",
        "zh-Hans": "消费邀请链接失败：%@",
        "zh-Hant": "消費邀請連結失敗：%@",
        "es": "No se pudo consumir el enlace de invitación: %@",
        "pt": "Falha ao consumir o link do convite: %@",
        "ar": "فشل استهلاك رابط الدعوة: %@",
        "hi": "आमंत्रण लिंक का उपभोग करने में विफल: %@",
        "fr": "Échec de l'utilisation du lien d'invitation : %@",
        "ta": "அழைப்பு இணைப்பைப் பயன்படுத்த முடியவில்லை: %@"
    },
    "添加附件": {
        "en": "Add attachment",
        "zh-Hans": "添加附件",
        "zh-Hant": "添加附件",
        "es": "Agregar archivo adjunto",
        "pt": "Adicionar anexo",
        "ar": "إضافة مرفق",
        "hi": "अनुलग्नक जोड़ें",
        "fr": "Ajouter une pièce jointe",
        "ta": "இணைப்பைச் சேர்க்கவும்"
    },
    "照片图库": {
        "en": "Photo Library",
        "zh-Hans": "照片图库",
        "zh-Hant": "照片圖庫",
        "es": "Biblioteca de fotos",
        "pt": "Biblioteca de fotos",
        "ar": "مكتبة الصور",
        "hi": "फोटो लाइब्रेरी",
        "fr": "Photothèque",
        "ta": "புகைப்பட நூலகம்"
    },
    "生日自动任务（年度循环）": {
        "en": "Birthday auto task (yearly recurrence)",
        "zh-Hans": "生日自动任务（年度循环）",
        "zh-Hant": "生日自動任務（年度循環）",
        "es": "Tarea automática de cumpleaños (recurrencia anual)",
        "pt": "Tarefa automática de aniversário (recorrência anual)",
        "ar": "مهمة تلقائية لعيد الميلاد (تكرار سنوي)",
        "hi": "जन्मदिन ऑटो कार्य (वार्षिक पुनरावृत्ति)",
        "fr": "Tâche automatique d'anniversaire (récurrence annuelle)",
        "ta": "பிறந்தநாள் ஆட்டோ டாஸ்க் (வருடாந்திர மறுநிகழ்வு)"
    },
    "用红框标记识别区域": {
        "en": "Mark area with red box",
        "zh-Hans": "用红框标记识别区域",
        "zh-Hant": "用紅框標記識別區域",
        "es": "Marcar el área con un cuadro rojo.",
        "pt": "Marque a área com uma caixa vermelha",
        "ar": "ضع علامة على المنطقة بالمربع الأحمر",
        "hi": "क्षेत्र को लाल बॉक्स से चिह्नित करें",
        "fr": "Marquer la zone avec un cadre rouge",
        "ta": "சிவப்பு பெட்டியுடன் பகுதியைக் குறிக்கவும்"
    },
    "男": {
        "en": "Male",
        "zh-Hans": "男",
        "zh-Hant": "男",
        "es": "masculino",
        "pt": "Masculino",
        "ar": "ذكر",
        "hi": "पुरुष",
        "fr": "Mâle",
        "ta": "ஆண்"
    },
    "登录成功": {
        "en": "Signed in successfully",
        "zh-Hans": "登录成功",
        "zh-Hant": "登入成功",
        "es": "Iniciado sesión correctamente",
        "pt": "Login feito com sucesso",
        "ar": "تم تسجيل الدخول بنجاح",
        "hi": "सफलतापूर्वक साइन इन किया गया",
        "fr": "Connecté avec succès",
        "ta": "வெற்றிகரமாக உள்நுழைந்துள்ளது"
    },
    "登录请求已发送，请完成授权后重试": {
        "en": "Sign-in request sent. Complete authorization and try again",
        "zh-Hans": "登录请求已发送，请完成授权后重试",
        "zh-Hant": "登入要求已發送，請完成授權後重試",
        "es": "Solicitud de inicio de sesión enviada. Completa la autorización y vuelve a intentarlo.",
        "pt": "Solicitação de login enviada. Conclua a autorização e tente novamente",
        "ar": "تم إرسال طلب تسجيل الدخول. أكمل التفويض وحاول مرة أخرى",
        "hi": "साइन-इन अनुरोध भेजा गया. प्राधिकरण पूर्ण करें और पुनः प्रयास करें",
        "fr": "Demande de connexion envoyée. Terminez l'autorisation et réessayez",
        "ta": "உள்நுழைவு கோரிக்கை அனுப்பப்பட்டது. அங்கீகாரத்தை நிறைவு செய்து, மீண்டும் முயற்சிக்கவும்"
    },
    "登录链接已发送，请检查邮箱并回到 App": {
        "en": "Sign-in link sent. Check your email and return to the app",
        "zh-Hans": "登录链接已发送，请检查邮箱并回到 App",
        "zh-Hant": "登入連結已發送，請檢查郵箱並回到 App",
        "es": "Enlace de inicio de sesión enviado. Revisa tu correo electrónico y regresa a la aplicación.",
        "pt": "Link de login enviado. Verifique seu e-mail e retorne ao aplicativo",
        "ar": "تم إرسال رابط تسجيل الدخول. تحقق من بريدك الإلكتروني وارجع إلى التطبيق",
        "hi": "साइन-इन लिंक भेजा गया. अपना ईमेल जांचें और ऐप पर वापस लौटें",
        "fr": "Lien de connexion envoyé. Vérifiez votre courrier électronique et revenez à l'application",
        "ta": "உள்நுழைவு இணைப்பு அனுப்பப்பட்டது. உங்கள் மின்னஞ்சலைச் சரிபார்த்து, பயன்பாட்டிற்குத் திரும்பவும்"
    },
    "确定要执行此操作吗？": {
        "en": "Are you sure you want to continue?",
        "zh-Hans": "确定要执行此操作吗？",
        "zh-Hant": "確定要執行此操作嗎？",
        "es": "¿Estás seguro de que quieres continuar?",
        "pt": "Tem certeza de que deseja continuar?",
        "ar": "هل أنت متأكد أنك تريد الاستمرار؟",
        "hi": "क्या आप वाकई जारी रखना चाहते हैं?",
        "fr": "Êtes-vous sûr de vouloir continuer ?",
        "ta": "நீங்கள் நிச்சயமாக தொடர விரும்புகிறீர்களா?"
    },
    "确认 %@ 的生日蛋糕预订": {
        "en": "Confirm birthday cake reservation for %@",
        "zh-Hans": "确认 %@ 的生日蛋糕预订",
        "zh-Hant": "確認 %@ 的生日蛋糕預訂",
        "es": "Confirmar reserva de tarta de cumpleaños para %@",
        "pt": "Confirme a reserva do bolo de aniversário para %@",
        "ar": "تأكيد حجز كعكة عيد ميلاد لـ %@",
        "hi": "%@ के लिए जन्मदिन केक आरक्षण की पुष्टि करें",
        "fr": "Confirmer la réservation du gâteau d'anniversaire pour %@",
        "ta": "%@க்கான பிறந்தநாள் கேக் முன்பதிவை உறுதிப்படுத்தவும்"
    },
    "移交群主": {
        "en": "Transfer Ownership",
        "zh-Hans": "移交群主",
        "zh-Hant": "移交群主",
        "es": "Transferir propiedad",
        "pt": "Transferir propriedade",
        "ar": "نقل الملكية",
        "hi": "स्वामित्व स्थानांतरित करें",
        "fr": "Transférer la propriété",
        "ta": "உரிமையை மாற்றவும்"
    },
    "移出后，该成员将无法再访问本群组的任务与信息。": {
        "en": "After removal, they can no longer access this group's tasks or messages.",
        "zh-Hans": "移出后，该成员将无法再访问本群组的任务与信息。",
        "zh-Hant": "移出後，該成員將無法再存取本群組的任務與資訊。",
        "es": "Después de la eliminación, ya no podrán acceder a las tareas ni a los mensajes de este grupo.",
        "pt": "Após a remoção, eles não poderão mais acessar as tarefas ou mensagens deste grupo.",
        "ar": "وبعد الإزالة، لم يعد بإمكانهم الوصول إلى مهام هذه المجموعة أو رسائلها.",
        "hi": "हटाने के बाद, वे अब इस समूह के कार्यों या संदेशों तक नहीं पहुंच सकते।",
        "fr": "Après la suppression, ils ne peuvent plus accéder aux tâches ou aux messages de ce groupe.",
        "ta": "அகற்றிய பிறகு, இந்தக் குழுவின் பணிகளையோ செய்திகளையோ அவர்களால் அணுக முடியாது."
    },
    "移除附件": {
        "en": "Remove attachment",
        "zh-Hans": "移除附件",
        "zh-Hant": "移除附件",
        "es": "Quitar archivo adjunto",
        "pt": "Remover anexo",
        "ar": "إزالة المرفق",
        "hi": "अनुलग्नक हटाएँ",
        "fr": "Supprimer la pièce jointe",
        "ta": "இணைப்பை அகற்று"
    },
    "第 %lld 张，共 %lld 张": {
        "en": "%1$lld of %2$lld",
        "zh-Hans": "第 %lld 张，共 %lld 张",
        "zh-Hant": "第 %lld 張，共 %lld 張",
        "es": "%1$lld of %2$lld",
        "pt": "%1$lld of %2$lld",
        "ar": "%1$lld of %2$lld",
        "hi": "%1$lld of %2$lld",
        "fr": "%1$lld of %2$lld",
        "ta": "%1$lld of %2$lld"
    },
    "等 %lld 个群组": {
        "en": " and %lld other groups",
        "zh-Hans": "等 %lld 个群组",
        "zh-Hant": "等 %lld 個群組",
        "es": "y %lld otros grupos",
        "pt": "e %lld outros grupos",
        "ar": "و%lld مجموعات أخرى",
        "hi": "और %lld अन्य समूह",
        "fr": "et %lld autres groupes",
        "ta": "மற்றும் %lld பிற குழுக்கள்"
    },
    "编辑资料": {
        "en": "Edit Profile",
        "zh-Hans": "编辑资料",
        "zh-Hant": "編輯資料",
        "es": "Editar archivo Pro",
        "pt": "Editar arquivo Pro",
        "ar": "تحرير Pro الملف",
        "hi": "Proफ़ाइल संपादित करें",
        "fr": "Modifier le fichier Pro",
        "ta": "Proஃபைலைத் திருத்தவும்"
    },
    "群组：%@": {
        "en": "Group: %@",
        "zh-Hans": "群组：%@",
        "zh-Hant": "群組：%@",
        "es": "Grupo: %@",
        "pt": "Grupo: %@",
        "ar": "المجموعة: %@",
        "hi": "समूह: %@",
        "fr": "Groupe : %@",
        "ta": "குழு: %@"
    },
    "群组与协作人数": {
        "en": "Groups & collaboration",
        "zh-Hans": "群组与协作人数",
        "zh-Hant": "群組與協作人數",
        "es": "Grupos y colaboración",
        "pt": "Grupos e colaboração",
        "ar": "المجموعات والتعاون",
        "hi": "समूह और सहयोग",
        "fr": "Groupes et collaboration",
        "ta": "குழுக்கள் மற்றும் ஒத்துழைப்பு"
    },
    "群组任务": {
        "en": "Group task",
        "zh-Hans": "群组任务",
        "zh-Hant": "群組任務",
        "es": "tarea grupal",
        "pt": "Tarefa de grupo",
        "ar": "مهمة المجموعة",
        "hi": "समूह कार्य",
        "fr": "Tâche de groupe",
        "ta": "குழு பணி"
    },
    "裁剪失败，请重试。": {
        "en": "Crop failed. Please try again.",
        "zh-Hans": "裁剪失败，请重试。",
        "zh-Hant": "裁剪失败，请重试。",
        "es": "La cosecha falló. Por favor inténtalo de nuevo.",
        "pt": "Falha na colheita. Por favor, tente novamente.",
        "ar": "فشل الاقتصاص. يرجى المحاولة مرة أخرى.",
        "hi": "फसल बर्बाद हो गई. कृपया पुन: प्रयास करें।",
        "fr": "La récolte a échoué. Veuillez réessayer.",
        "ta": "செதுக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்."
    },
    "识别区域无效，请调整红框后重试。": {
        "en": "Invalid recognition area. Adjust the red box and try again.",
        "zh-Hans": "识别区域无效，请调整红框后重试。",
        "zh-Hant": "識別區域無效，請調整紅框後重試。",
        "es": "Área de reconocimiento no válida. Ajuste el cuadro rojo y vuelva a intentarlo.",
        "pt": "Área de reconhecimento inválida. Ajuste a caixa vermelha e tente novamente.",
        "ar": "منطقة التعرف غير صالحة. اضبط المربع الأحمر وحاول مرة أخرى.",
        "hi": "अमान्य मान्यता क्षेत्र. लाल बॉक्स को समायोजित करें और पुनः प्रयास करें।",
        "fr": "Zone de reconnaissance invalide. Ajustez la case rouge et réessayez.",
        "ta": "தவறான அங்கீகாரப் பகுதி. சிவப்பு பெட்டியை சரிசெய்து மீண்டும் முயற்சிக்கவும்."
    },
    "识别此区域": {
        "en": "Recognize this area",
        "zh-Hans": "识别此区域",
        "zh-Hant": "識別此區域",
        "es": "Reconocer esta zona",
        "pt": "Reconheça esta área",
        "ar": "التعرف على هذه المنطقة",
        "hi": "इस क्षेत्र को पहचानें",
        "fr": "Reconnaître cette zone",
        "ta": "இந்த பகுதியை அங்கீகரிக்கவும்"
    },
    "该邀请链接已被使用（409）。": {
        "en": "This invite link has already been used (409).",
        "zh-Hans": "该邀请链接已被使用（409）。",
        "zh-Hant": "此邀請連結已被使用（409）。",
        "es": "Este enlace de invitación ya se ha utilizado (409).",
        "pt": "Este link de convite já foi usado (409).",
        "ar": "تم استخدام رابط الدعوة هذا بالفعل (409).",
        "hi": "यह आमंत्रण लिंक पहले ही उपयोग किया जा चुका है (409)।",
        "fr": "Ce lien d'invitation a déjà été utilisé (409).",
        "ta": "இந்த அழைப்பு இணைப்பு ஏற்கனவே பயன்படுத்தப்பட்டது (409)."
    },
    "该邀请链接已过期（410）。": {
        "en": "This invite link has expired (410).",
        "zh-Hans": "该邀请链接已过期（410）。",
        "zh-Hant": "此邀請連結已過期（410）。",
        "es": "Este enlace de invitación ha caducado (410).",
        "pt": "Este link de convite expirou (410).",
        "ar": "انتهت صلاحية رابط الدعوة هذا (410).",
        "hi": "यह आमंत्रण लिंक समाप्त हो गया है (410)।",
        "fr": "Ce lien d'invitation a expiré (410).",
        "ta": "இந்த அழைப்பு இணைப்பு காலாவதியானது (410)."
    },
    "请先登录以启用云端同步": {
        "en": "Sign in to enable cloud sync",
        "zh-Hans": "请先登录以启用云端同步",
        "zh-Hant": "請先登入啟用雲端同步",
        "es": "Inicia sesión para habilitar la sincronización en la nube",
        "pt": "Faça login para ativar a sincronização na nuvem",
        "ar": "قم بتسجيل الدخول لتمكين المزامنة السحابية",
        "hi": "क्लाउड सिंक सक्षम करने के लिए साइन इन करें",
        "fr": "Connectez-vous pour activer la synchronisation cloud",
        "ta": "கிளவுட் ஒத்திசைவை இயக்க உள்நுழையவும்"
    },
    "请发送邮件至 %@。": {
        "en": "Please email %@.",
        "zh-Hans": "请发送邮件至 %@。",
        "zh-Hant": "請發送郵件至 %@。",
        "es": "Envíe un correo electrónico a %@.",
        "pt": "Por favor, envie um e-mail para %@.",
        "ar": "يرجى إرسال بريد إلكتروني إلى %@.",
        "hi": "कृपया %@ ईमेल करें।",
        "fr": "Veuillez envoyer un e-mail à %@.",
        "ta": "தயவுசெய்து மின்னஞ்சல் %@."
    },
    "请输入分享链接中的 sig 参数": {
        "en": "Enter the sig parameter from the share link",
        "zh-Hans": "请输入分享链接中的 sig 参数",
        "zh-Hant": "請輸入分享連結中的 sig 參數",
        "es": "Ingrese el parámetro sig desde el enlace para compartir",
        "pt": "Insira o parâmetro sig do link de compartilhamento",
        "ar": "أدخل المعلمة sig من رابط المشاركة",
        "hi": "शेयर लिंक से sig पैरामीटर दर्ज करें",
        "fr": "Entrez le paramètre sig à partir du lien de partage",
        "ta": "பகிர்வு இணைப்பிலிருந்து sig அளவுருவை உள்ளிடவும்"
    },
    "请选择您要进入的群组": {
        "en": "Choose a group to open",
        "zh-Hans": "请选择您要进入的群组",
        "zh-Hant": "請選擇您要進入的群組",
        "es": "Elige un grupo para abrir",
        "pt": "Escolha um grupo para abrir",
        "ar": "اختر مجموعة لفتحها",
        "hi": "खोलने के लिए एक समूह चुनें",
        "fr": "Choisissez un groupe à ouvrir",
        "ta": "திறக்க ஒரு குழுவைத் தேர்ந்தெடுக்கவும்"
    },
    "读取到原始图片数据为空，请重新选择。": {
        "en": "Image data was empty. Please choose again.",
        "zh-Hans": "读取到原始图片数据为空，请重新选择。",
        "zh-Hant": "讀取到原始圖片資料為空，請重新選擇。",
        "es": "Los datos de la imagen estaban vacíos. Por favor elige de nuevo.",
        "pt": "Os dados da imagem estavam vazios. Por favor, escolha novamente.",
        "ar": "بيانات الصورة كانت فارغة. الرجاء الاختيار مرة أخرى.",
        "hi": "छवि डेटा खाली था. कृपया पुनः चुनें.",
        "fr": "Les données d'image étaient vides. Veuillez choisir à nouveau.",
        "ta": "படத்தின் தரவு காலியாக இருந்தது. மீண்டும் தேர்வு செய்யவும்."
    },
    "购买 %@ 的生日礼物": {
        "en": "Buy birthday gift for %@",
        "zh-Hans": "购买 %@ 的生日礼物",
        "zh-Hant": "購買 %@ 的生日禮物",
        "es": "Compra regalo de cumpleaños para %@",
        "pt": "Compre presente de aniversário para %@",
        "ar": "اشتري هدية عيد ميلاد لـ %@",
        "hi": "%@ के लिए जन्मदिन का उपहार खरीदें",
        "fr": "Achetez un cadeau d'anniversaire pour %@",
        "ta": "%@க்கு பிறந்தநாள் பரிசை வாங்கவும்"
    },
    "身份证": {
        "en": "ID Card",
        "zh-Hans": "身份证",
        "zh-Hant": "身分證",
        "es": "Tarjeta de identificación",
        "pt": "Cartão de identificação",
        "ar": "بطاقة الهوية",
        "hi": "आईडी कार्ड",
        "fr": "Carte d'identité",
        "ta": "அடையாள அட்டை"
    },
    "身高": {
        "en": "Height",
        "zh-Hans": "身高",
        "zh-Hant": "身高",
        "es": "altura",
        "pt": "Altura",
        "ar": "الارتفاع",
        "hi": "ऊंचाई",
        "fr": "Hauteur",
        "ta": "உயரம்"
    },
    "轻点以全屏查看，可左右滑动切换": {
        "en": "Double tap for full screen. Swipe left or right to switch.",
        "zh-Hans": "轻点以全屏查看，可左右滑动切换",
        "zh-Hant": "輕點以全螢幕查看，可左右滑動切換",
        "es": "Toca dos veces para ver la pantalla completa. Desliza hacia la izquierda o hacia la derecha para cambiar.",
        "pt": "Toque duas vezes para tela cheia. Deslize para a esquerda ou para a direita para alternar.",
        "ar": "انقر نقرًا مزدوجًا لملء الشاشة. اسحب لليسار أو لليمين للتبديل.",
        "hi": "पूर्ण स्क्रीन के लिए दो बार टैप करें. स्विच करने के लिए बाएँ या दाएँ स्वाइप करें।",
        "fr": "Appuyez deux fois pour passer en plein écran. Faites glisser votre doigt vers la gauche ou la droite pour changer.",
        "ta": "முழுத் திரைக்கு இருமுறை தட்டவும். மாற இடது அல்லது வலது ஸ்வைப் செய்யவும்."
    },
    "输入群组名称…": {
        "en": "Enter group name…",
        "zh-Hans": "输入群组名称…",
        "zh-Hant": "輸入群組名稱…",
        "es": "Introduzca el nombre del grupo...",
        "pt": "Digite o nome do grupo…",
        "ar": "أدخل اسم المجموعة...",
        "hi": "समूह का नाम दर्ज करें...",
        "fr": "Entrez le nom du groupe…",
        "ta": "குழுவின் பெயரை உள்ளிடவும்…"
    },
    "输入群组描述（选填）": {
        "en": "Group description (optional)",
        "zh-Hans": "输入群组描述（选填）",
        "zh-Hant": "輸入群組描述（選填）",
        "es": "Descripción del grupo (opcional)",
        "pt": "Descrição do grupo (opcional)",
        "ar": "وصف المجموعة (اختياري)",
        "hi": "समूह विवरण (वैकल्पिक)",
        "fr": "Description du groupe (facultatif)",
        "ta": "குழு விளக்கம் (விரும்பினால்)"
    },
    "输入群组描述（选填）…": {
        "en": "Enter group description (optional)…",
        "zh-Hans": "输入群组描述（选填）…",
        "zh-Hant": "輸入群組描述（選填）…",
        "es": "Ingrese la descripción del grupo (opcional)…",
        "pt": "Insira a descrição do grupo (opcional)…",
        "ar": "أدخل وصف المجموعة (اختياري)...",
        "hi": "समूह विवरण दर्ज करें (वैकल्पिक)…",
        "fr": "Entrez la description du groupe (facultatif)…",
        "ta": "குழு விளக்கத்தை உள்ளிடவும் (விரும்பினால்)…"
    },
    "通过 Apple 登录": {
        "en": "Sign in with Apple",
        "zh-Hans": "通过 Apple 登录",
        "zh-Hant": "透過 Apple 登入",
        "es": "Continuar con Apple",
        "pt": "Continue com Apple",
        "ar": "تواصل مع Apple",
        "hi": "Apple के साथ जारी रखें",
        "fr": "Continuez avec Apple",
        "ta": "Apple உடன் தொடரவும்"
    },
    "邀请链接无效或已被篡改。": {
        "en": "Invite link is invalid or has been tampered with.",
        "zh-Hans": "邀请链接无效或已被篡改。",
        "zh-Hant": "邀請連結無效或已被篡改。",
        "es": "El enlace de invitación no es válido o ha sido manipulado.",
        "pt": "O link de convite é inválido ou foi adulterado.",
        "ar": "رابط الدعوة غير صالح أو تم العبث به.",
        "hi": "आमंत्रण लिंक अमान्य है या उसके साथ छेड़छाड़ की गई है।",
        "fr": "Le lien d’invitation n’est pas valide ou a été falsifié.",
        "ta": "அழைப்பு இணைப்பு தவறானது அல்லது சிதைக்கப்பட்டுள்ளது."
    },
    "邀请链接缺少签名参数。": {
        "en": "Invite link is missing the signature parameter.",
        "zh-Hans": "邀请链接缺少签名参数。",
        "zh-Hant": "邀請連結缺少簽名參數。",
        "es": "Al enlace de invitación le falta el parámetro de naturaleza sig.",
        "pt": "O link de convite está faltando no parâmetro signature.",
        "ar": "رابط الدعوة يفتقد المعلمة signature.",
        "hi": "आमंत्रण लिंक में signature पैरामीटर गुम है।",
        "fr": "Le lien d'invitation ne contient pas le paramètre signature.",
        "ta": "அழைப்பு இணைப்பில் signature அளவுரு இல்லை."
    },
    "重拍": {
        "en": "Retake",
        "zh-Hans": "重拍",
        "zh-Hant": "重拍",
        "es": "Retomar",
        "pt": "Retomar",
        "ar": "إعادة الالتقاط",
        "hi": "पुनः लेना",
        "fr": "Reprendre",
        "ta": "மீண்டும் எடுக்கவும்"
    },
    "附件数量已达上限。": {
        "en": "Attachment limit reached.",
        "zh-Hans": "附件数量已达上限。",
        "zh-Hant": "附件數量已達上限。",
        "es": "Se alcanzó el límite de archivos adjuntos.",
        "pt": "Limite de anexos atingido.",
        "ar": "تم الوصول إلى حد المرفقات.",
        "hi": "अनुलग्नक की सीमा पूरी हो गई.",
        "fr": "Limite de pièces jointes atteinte.",
        "ta": "இணைப்பு வரம்பை அடைந்துவிட்டது."
    },
    "陪伴 %@，祝生日快乐！": {
        "en": "Spend time with %@ and wish a Happy Birthday!",
        "zh-Hans": "陪伴 %@，祝生日快乐！",
        "zh-Hant": "陪伴 %@，祝生日快樂！",
        "es": "¡Pasa tiempo con %@ y desea un feliz cumpleaños!",
        "pt": "Passe algum tempo com %@ e deseje um feliz aniversário!",
        "ar": "اقضِ بعض الوقت مع %@ وأتمنى عيد ميلاد سعيدًا!",
        "hi": "%@ के साथ समय बिताएं और जन्मदिन की शुभकामनाएं दें!",
        "fr": "Passez du temps avec %@ et souhaitez un joyeux anniversaire !",
        "ta": "%@ உடன் நேரத்தை செலவிடுங்கள் மற்றும் பிறந்தநாள் வாழ்த்துக்கள்!"
    },
    "领取成功！您的 Pro 权益已激活至 %lld 年。": {
        "en": "Success! Your Pro benefits are active until %lld.",
        "zh-Hans": "领取成功！您的 Pro 权益已激活至 %lld 年。",
        "zh-Hant": "領取成功！您的 Pro 權益已啟用至 %lld 年。",
        "es": "¡Éxito! Tus beneficios Pro están activos hasta el %lld.",
        "pt": "Sucesso! Seus benefícios Pro estarão ativos até %lld.",
        "ar": "النجاح! فوائد Pro الخاصة بك نشطة حتى %lld.",
        "hi": "सफलता! आपके Pro लाभ %lld तक सक्रिय हैं।",
        "fr": "Succès ! Vos avantages Pro sont actifs jusqu'au %lld.",
        "ta": "வெற்றி! உங்களின் Pro பலன்கள் %lld வரை செயலில் இருக்கும்."
    },
    "领取成功！您的 Pro 权益已激活至 2027 年。": {
        "en": "Success! Your Pro benefits are active until 2027.",
        "zh-Hans": "领取成功！您的 Pro 权益已激活至 2027 年。",
        "zh-Hant": "領取成功！您的 Pro 權益已啟用至 2027 年。",
        "es": "¡Éxito! Tus beneficios Pro están activos hasta 2027.",
        "pt": "Sucesso! Seus benefícios Pro estarão ativos até 2027.",
        "ar": "النجاح! مزايا Pro الخاصة بك نشطة حتى عام 2027.",
        "hi": "सफलता! आपके Pro लाभ 2027 तक सक्रिय हैं।",
        "fr": "Succès ! Vos avantages Pro sont actifs jusqu'en 2027.",
        "ta": "வெற்றி! உங்களின் Pro பலன்கள் 2027 வரை செயலில் இருக்கும்."
    },
    "验证码已发送，请完成验证后重试": {
        "en": "Verification code sent. Complete verification and try again",
        "zh-Hans": "验证码已发送，请完成验证后重试",
        "zh-Hant": "驗證碼已發送，請完成驗證後重試",
        "es": "Código de verificación enviado. Completa la verificación e inténtalo de nuevo.",
        "pt": "Código de verificação enviado. Conclua a verificação e tente novamente",
        "ar": "تم إرسال رمز التحقق. أكمل عملية التحقق ثم حاول مرة أخرى",
        "hi": "सत्यापन कोड भेजा गया. सत्यापन पूरा करें और पुनः प्रयास करें",
        "fr": "Code de vérification envoyé. Terminez la vérification et réessayez",
        "ta": "சரிபார்ப்புக் குறியீடு அனுப்பப்பட்டது. சரிபார்ப்பை முடித்து மீண்டும் முயலவும்"
    },
    "图片预览不可用": {
        "en": "Image preview unavailable",
        "zh-Hans": "图片预览不可用",
        "zh-Hant": "圖片預覽不可用",
        "es": "Vista previa de imagen no disponible",
        "pt": "Pré-visualização de imagem indisponível",
        "ar": "معاينة الصورة غير متاحة",
        "hi": "छवि पूर्वावलोकन उपलब्ध नहीं है",
        "fr": "Aperçu de l'image indisponible",
        "ta": "பட முன்னோட்டம் கிடைக்கவில்லை"
    }
}
